name: integrated_rtrw
description: "Sistem Informasi Terpadu RW & RT (Integrated RTRW) - Multi Tenant Mobile App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase & Auth
  supabase_flutter: ^2.6.0
  
  # State Management & DI
  provider: ^6.1.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
